### ISSUE TITLE
Its not working for me

### ISSUE THREAD

**Issue by bufdex** [hrt/BrawlBot#5]
it says:
Traceback (most recent call last):
  File "C:\Users\Juliano\Desktop\BrawlBot-master\memorpy-master\play.py", line 341, in <module>
    main()
  File "C:\Users\Juliano\Desktop\BrawlBot-master\memorpy-master\play.py", line 18, in main
    entity_pointers.remove(local_ptr)
ValueError: list.remove(x): x not in list
>>> 

![Screenshot_2](https://user-images.githubusercontent.com/69868410/90559413-f2402480-e173-11ea-8b84-66e590a262f9.png)
what should i do?

**Comment by hrt** [comment]
@bufdex
If you've correctly found your local entity pointer and for some reason you're not seeing it in the entity list like above then you could just wrap it in a try except.

But this probably suggests either

- Your entity list isn't finding all the entities - you should see the same number of entities as players in the game. If this is the case, you could try increasing the region to search.

or

- The local entity pointer you're using is different to the one inside the entity list. Perhaps you could find the local entity pointer offsets that ends up at an address similar to the entities.

**Comment by bufdex** [comment]
do u have discord?

**Comment by Zayoe4** [comment]
Add me, I got it to work.
Discord: Zayoe#0001

**Comment by n1ce0n3** [comment]
> Add me, I got it to work.
> Discord: Zayoe#0001

Hey, could you please contact me on discord n1ce0n3#7250, since it says your discord is wrong.  Thanks in advance,.

**Comment by n1ce0n3** [comment]
Okay, I'm not really confident with the python, I'd say i'm still learning it.
So at this point I've got the offsets mentioned by @Zayoe4 working and its all good, but there is one issue I've managed to get debugged, and can't seem to find a way of fixing it.
At the main function when it goes to the check local and target entities - after you press DODGE (only happens with the dodge) ingame manually (not sure if it works if it gets executed by the script) - the local players "in_stun" variable always returns that: 
local.in_stun = {int} 150240.
Actually I just figured by changing the control mode to the CPU in practice, if you dodge while playing the enemy - it returns a positive number constantly too. So I guess it's the "stun_offset" offset not being correct?
I really suck at reversing, especially in adobe air stuff, so please, seeking some help to slove that issue. Thanks in advance.
@Zayoe4 @hrt

**Comment by taohabo** [comment]
@Zayoe4 please contact me discord : Thien1994#5618
